version: "3.7"

services:
  database_bulletins:
    image: postgres
    container_name: database_bulletins
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=bulletins
      - POSTGRES_DB=bulletins
    volumes:
      - pgdata:/data/postgres
  bulletins:
    build: ./backend
    container_name: bulletins
    ports:
      - 3333:3333
    links:
      - database_bulletins
    depends_on:
      - database_bulletins
  web:
    build: ./frontend
    container_name: bulletins-web
    ports:
      - 8080:8080
    links:
      - bulletins

volumes:
  pgdata:
    driver: local
